# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motorCtrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 504)
        self.text = QtWidgets.QTextEdit(Form)
        self.text.setGeometry(QtCore.QRect(230, 170, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.sendBtn = QtWidgets.QPushButton(Form)
        self.sendBtn.setGeometry(QtCore.QRect(480, 170, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sendBtn.setFont(font)
        self.sendBtn.setObjectName("sendBtn")
        self.speed = QtWidgets.QLabel(Form)
        self.speed.setGeometry(QtCore.QRect(270, 90, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.speed.setFont(font)
        self.speed.setAlignment(QtCore.Qt.AlignCenter)
        self.speed.setObjectName("speed")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sendBtn.setText(_translate("Form", "send"))
        self.speed.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
